kind: pipeline
name: default

steps:
- name: install
  image: node:10.15.0
  commands:
    - npm install

- name: build
  image: node:10.15.0
  commands:
    - npm run build

- name: start
  image: node:10.15.0
  detach: true
  commands:
    - npm run start
