version: 0.2

phases:
  install:
    commands:
      - npm install
    finally:
      - npm i -g pm2
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - pm2 start ecosystem.config.js
