[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; script-src 'self' *.jsdelivr.net; style-src 'self' *.googleapis.com *.jsdelivr.net; img-src 'self'; font-src 'self' *.gstatic.com; object-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'self'"
