title: 'Global Settings'
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_name
            field:
              character_limit: 0
              type: text
              display: 'Site Name'
          -
            handle: social
            field:
              fields:
                -
                  handle: name
                  field:
                    type: text
                    display: Name
                -
                  handle: url
                  field:
                    character_limit: 0
                    type: text
                    display: URL
                -
                  handle: icon_name
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: 'Icon Name'
                    icon: text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
              mode: table
              add_row: 'Add Link'
              reorderable: true
              type: grid
              instructions: 'Set any social media links'
              display: Social
              instructions_position: above
              listable: hidden
              visibility: visible
              replicator_preview: true
              fullscreen: true
              hide_display: false
